apiVersion: v1
kind: ServiceMonitor
metadata:
  name: kafka-metrics
  namespace: nxr-infrastructure
  labels:
    app: kafka
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics

---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: kafka-jmx-metrics
  namespace: nxr-infrastructure
  labels:
    app: kafka
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka
  endpoints:
    - port: jmx
      interval: 30s
      path: /metrics

