apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: nxr-monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-kube-prometheus-prometheus:9090
        isDefault: true
        editable: true
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        editable: true
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo-distributed-query-frontend:3100
        editable: true

