apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-service
  namespace: stack4things
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleet-service
  template:
    metadata:
      labels:
        app: fleet-service
    spec:
      containers:
        - name: fleet-service
          image: ghcr.io/stack4things/fleet-service:latest
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
