apiVersion: apps/v1
kind: Deployment
metadata:
  name: execution-service
  namespace: nxr
  labels:
    app: execution-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: execution-service
  template:
    metadata:
      labels:
        app: execution-service
    spec:
      serviceAccountName: nexora-service
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      initContainers:
        - name: wait-mysql
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z mysql 3306; do echo waiting for mysql; sleep 2; done']
        - name: wait-kafka
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z kafka 9092; do echo waiting for kafka; sleep 2; done']
        - name: wait-redis
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z redis 6379; do echo waiting for redis; sleep 2; done']
      containers:
        - name: execution-service
          image: nexora/execution-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8002
          envFrom:
            - configMapRef:
                name: nexora-config
            - secretRef:
                name: nexora-internal
            - secretRef:
                name: nexora-db
          env:
            - name: PORT
              value: "8002"
          readinessProbe:
            httpGet:
              path: /ready
              port: 8002
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: execution-service
  namespace: nxr
spec:
  selector:
    app: execution-service
  ports:
    - port: 8002
      targetPort: 8002
