apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: device-service-hpa
  namespace: nxr
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: device-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: execution-service-hpa
  namespace: nxr
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: execution-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: plugin-service-hpa
  namespace: nxr
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: plugin-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
