apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nxr
resources:
  - ../../base
  - ../../secrets.example.yaml

configMapGenerator:
  - name: nexora-production-config
    literals:
      - ENVIRONMENT=production
      - AUTH_ENABLED=true
      - AUTH_DEV_BYPASS_ENABLED=false
      - KAFKA_REQUIRED=true
      - REDIS_REQUIRED=true
      - KEYCLOAK_URL=https://keycloak.example.org
      - KEYCLOAK_REALM=nxr
      - KEYCLOAK_JWKS_URL=https://keycloak.example.org/realms/nxr/protocol/openid-connect/certs
      - AUTH_PLATFORM_ADMIN_ROLE=platform-admin
      - AUTH_TENANT_ADMIN_ROLE=tenant-admin
      - AUTH_OPERATOR_ROLE=operator
      - AUTH_VIEWER_ROLE=viewer

patches:
  - path: production-env-patch.yaml
